import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/home.module.scss";
import Layout from "../components/Layout";
import Link from "next/link";

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Home</title>
			</Head>
			<section className={styles.home}>
				<div className={styles.hero}>
					<div className={styles.hero__text}>
						<span className={styles.hero__text_secondary}>Projects</span>
						<span className={styles.hero__text_primary}>SHOWCASE</span>
						<span className={styles.hero__text_secondary}>app</span>
					</div>
					<div className={styles.hero__images}>
						<img src="/nextjs-short.svg" alt="nextjs icon" />
						<span className={styles.plus}>+</span>
						<img src="/react.svg" alt="react icon" />
					</div>
				</div>
				<p className={styles.text_section}>
					This app was created with the goal of putting into practice the
					knowledge that I acquired during the Nextjs Introduction course that
					Vercel offers in their website. To couple with that, I decided to also
					showcase some of the projects that I made when following along the
					Learn React for free course offered by Scrimba.
				</p>
				<Link href={"/projects"}>
					<button className={styles.cta_button}>Check out the Projects!</button>
				</Link>
			</section>
		</Layout>
	);
}

/*

projects-data.json is where the data about each project is stored, including its title, description and url.

dynamic routing will be used to create the pages for each project. The project page will receive as props the array of all the project urls, the data about the current project and thats it.

*/

/*

<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>

*/
